Fixes "Error: Cannot find module 'genetic'"
"main" in package.json was pointing to the "/lib" (absolute) directory instead of "./lib" (local relative)